version: "3"

services:
  api:
    build:
      context: ./api
    env_file:
      - ./api/.env.local
    ports:
      - "3002:3002"
    depends_on:
      - mongodb

  ui:
    build:
      context: ./ui
    env_file:
      - ./ui/.env.local
    ports:
      - "8080:80"

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
