version: '3'

services:
  api:
    image: ghcr.io/daniel-gabriel/mustachio-recipes/api:latest
    env_file:
      - .env.api
    ports:
      - "3002:3002"
    depends_on:
      - mongodb

  ui:
    image: ghcr.io/daniel-gabriel/mustachio-recipes/ui:latest
    env_file:
      - .env.ui
    ports:
      - "80:80"

  mongodb:
    image: "mongo:latest"
    env_file:
      - .env.mongo
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
