version: '3'

services:
  api:
    build:
      context: ./api
    ports:
      - "3002:3000"
    depends_on:
      - mongodb

  ui:
    build:
      context: ./ui
    ports:
      - "8080:80"

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
