export class Config {
    public static API_BASE_URL = window.APP_CONFIG.API_BASE_URL;
    public static FIREBASE_API_KEY = window.APP_CONFIG.FIREBASE_API_KEY;
    public static FIREBASE_AUTH_DOMAIN = window.APP_CONFIG.FIREBASE_AUTH_DOMAIN;
    public static FIREBASE_PROJECT_ID = window.APP_CONFIG.FIREBASE_PROJECT_ID;
    public static FIREBASE_STORAGE_BUCKET = window.APP_CONFIG.FIREBASE_STORAGE_BUCKET;
    public static FIREBASE_MESSAGING_SENDER_ID = window.APP_CONFIG.FIREBASE_MESSAGING_SENDER_ID;
    public static FIREBASE_APP_ID = window.APP_CONFIG.FIREBASE_APP_ID;
}