name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      force-ui-build:
        description: Forces a UI build when checked
        required: false
        default: false
      force-api-build:
        description: Forces an API build when checked
        required: false
        default: false
  push:
    branches:
      - '*'
    tags:
      - v*

jobs:
  build_and_push:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    outputs:
      ui-changed: ${{ steps.check-changes.outputs.ui-changed }}
      api-changed: ${{ steps.check-changes.outputs.api-changed }}
      docker-ui-tag: ${{ steps.tags.outputs.uiTag }}
      docker-api-tag: ${{ steps.tags.outputs.apiTag }}
      ui-version: ${{ steps.gitversion-ui.outputs.fullSemVer }}
      api-version: ${{ steps.gitversion-api.outputs.fullSemVer }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for changes
        id: check-changes
        run: |
          if [[ "${{ github.event.inputs.force-ui-build }}" == "true" ]] || ! git diff --quiet HEAD^ HEAD -- ./ui; then
            echo "UI - setting to true"
            echo "ui-changed=true" >> $GITHUB_OUTPUT
          else
            echo "UI - setting to false"
            echo "ui-changed=false" >> $GITHUB_OUTPUT
          fi
          
          if [[ "${{ github.event.inputs.force-api-build }}" == "true" ]] || ! git diff --quiet HEAD^ HEAD -- ./api; then
            echo "API - setting to true"
            echo "api-changed=true" >> $GITHUB_OUTPUT
          else
            echo "API - setting to false"
            echo "api-changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Install GitVersion
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: "5.x"

      # Version for API
      - name: Run GitVersion for API
        if: ${{ !startsWith(github.ref, 'refs/tags/') && steps.check-changes.outputs.api-changed == 'true' }}
        uses: gittools/actions/gitversion/execute@v0.9.15
        id: gitversion-api
        with:
          useConfigFile: true
          configFilePath: api/GitVersion.yml

#      - name: Make version.txt file for API
#        if: ${{ !startsWith(github.ref, 'refs/tags/') && steps.check-changes.outputs.api-changed == 'true' }}
#        run: |
#          echo -n "${{ steps.gitversion-api.outputs.fullSemVer }}" > api/apiVersion.txt

      # Version for UI
      - name: Run GitVersion for UI
        if: ${{ !startsWith(github.ref, 'refs/tags/') && steps.check-changes.outputs.ui-changed == 'true' }}
        uses: gittools/actions/gitversion/execute@v0.9.15
        id: gitversion-ui
        with:
          useConfigFile: true
          configFilePath: ui/GitVersion.yml

#      - name: Make version.txt file for UI
#        if: ${{ !startsWith(github.ref, 'refs/tags/') && steps.check-changes.outputs.ui-changed == 'true' }}
#        run: |
#          echo -n "${{ steps.gitversion-ui.outputs.fullSemVer }}" > ui/uiVersion.txt

      # Upload the version artefacts
      - name: Publish the docker-compose file
        uses: actions/upload-artifact@v3
        with:
          name: Docker
          path: |
            docker-compose.*.yml

      - name: Make docker image tags
        id: tags
        run: |
          echo "apiTag=${{ github.repository }}/api:${{ steps.gitversion-api.outputs.fullSemVer }}" >> $GITHUB_OUTPUT
          echo "uiTag=${{ github.repository }}/ui:${{ steps.gitversion-ui.outputs.fullSemVer }}" >> $GITHUB_OUTPUT

      - name: Build API Docker image
        if: ${{ steps.check-changes.outputs.api-changed == 'true' }}
        run: |
          cd api
          docker build -t ghcr.io/${{ steps.tags.outputs.apiTag }} .
      - name: Build UI Docker image
        if: ${{ steps.check-changes.outputs.ui-changed == 'true' }}
        run: |
          cd ui
          docker build -t ghcr.io/${{ steps.tags.outputs.uiTag }} .

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push API Docker image
        if: ${{ steps.check-changes.outputs.api-changed == 'true' }}
        run: docker push ghcr.io/${{ steps.tags.outputs.apiTag }}

      - name: Push UI Docker image
        if: ${{ steps.check-changes.outputs.ui-changed == 'true' }}
        run: docker push ghcr.io/${{ steps.tags.outputs.uiTag }}

  deploy-prod:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      # wait for an approval on the created github issue for up to 3 minutes
      - uses: trstringer/manual-approval@v1
        timeout-minutes: 3
        with:
          secret: ${{ github.TOKEN }}
          approvers: daniel-gabriel
          minimum-approvals: 1
          issue-title: "Deploying ${{ github.ref_name }} to prod from docker image"
          issue-body: "Comment 'approve' on the new issue titled ${{github.ref_name}} to approve release."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

      - uses: actions/download-artifact@v3
        with:
          name: Docker
          path: docker
#
#      - name: Get code version
#        id: versions
#        run: |
#          uiVersion=$(cat versions/ui/uiVersion.txt)
#          echo "uiVersion=$uiVersion" >> $GITHUB_OUTPUT
#          echo "ui version: $uiVersion"
#          apiVersion=$(cat versions/api/apiVersion.txt)
#          echo "apiVersion=$apiVersion" >> $GITHUB_OUTPUT
#          echo "api version: $apiVersion"

      # make a release for the UI
      - name: Bump version and push UI tag
        if: ${{ needs.build_and_push.outputs.ui-changed == 'true' }}
        id: tag-ui-version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ui-${{ needs.build_and_push.outputs.ui-version }}

      - name: Create a UI GitHub release
        if: ${{ needs.build_and_push.outputs.ui-changed == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          tag: ui-${{ needs.build_and_push.outputs.ui-version }}
          name: Release ui-${{ needs.build_and_push.outputs.ui-version }}
          body: ${{ steps.tag-ui-version.outputs.changelog }}

      # make a release for the API
      - name: Bump version and push API tag
        if: ${{ needs.build_and_push.outputs.api-changed == 'true' }}
        id: tag-api-version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: api-${{ needs.build_and_push.outputs.api-version }}

      - name: Create an API GitHub release
        if: ${{ needs.build_and_push.outputs.api-changed == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          tag: api-${{ needs.build_and_push.outputs.api-version }}
          name: Release api-${{ needs.build_and_push.outputs.api-version }}
          body: ${{ steps.tag-api-version.outputs.changelog }}

      - name: Deploy to Digital Ocean
        env:
          DROPLET_PRIVATE_KEY: ${{ secrets.DIGITAL_OCEAN_DROPLET_SSH_PRIVATE_KEY }}
          DROPLET_ADDRESS: ${{ vars.DIGITAL_OCEAN_DROPLET_IP }}
          DROPLET_USER: ${{ vars.DIGITAL_OCEAN_DROPLET_USER }}
          GHCR_USER: ${{ vars.GHCR_USER }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          echo "$DROPLET_PRIVATE_KEY" > deploy_key
          chmod 600 deploy_key
          
          # copy docker-compose to the droplet
          scp -i deploy_key -o StrictHostKeyChecking=no ./docker/docker-compose.*.yml "$DROPLET_USER@$DROPLET_ADDRESS:/opt/mustachio"

          ssh -i deploy_key -o StrictHostKeyChecking=no -o SendEnv=GHCR_TOKEN -o SendEnv=GHCR_USER "$DROPLET_USER@$DROPLET_ADDRESS" <<'ENDSSH'
            # Log in to GitHub Container Registry
            echo "$GHCR_TOKEN" | docker login ghcr.io -u $GHCR_USER --password-stdin
            
            # Pull the updated Docker images if they have changed
            if [ "${{ needs.build_and_push.outputs.api-changed }}" == "true" ]; then
              docker pull ghcr.io/${{ needs.build_and_push.outputs.docker-api-tag }}
            fi
            
            if [ "${{ needs.build_and_push.outputs.ui-changed }}" == "true" ]; then
              docker pull ghcr.io/${{ needs.build_and_push.outputs.docker-ui-tag }}
            fi
            
            cd /opt/mustachio
            docker-compose up -d
          ENDSSH